# KNN

In [ ]:
import pandas as pd                                              # Data Manipulation
import numpy as np                                               # Data Manipulation
import sklearn                                                   # ML Support
from sklearn.neighbors import KNeighborsClassifier as knn        # KNN Classifier

In [ ]:
df = pd.read_csv("/content/knn.csv")
df

X  Y Class
0  2  4     N
1  4  6     N
2  4  4     P
3  4  2     N
4  6  4     N
5  6  2     P

In [ ]:
x=df.iloc[:,:-1].values
y=df.iloc[:,2].values

In [ ]:
x

array([[2, 4],
       [4, 6],
       [4, 4],
       [4, 2],
       [6, 4],
       [6, 2]])

In [ ]:
y

array(['N', 'N', 'P', 'N', 'N', 'P'], dtype=object)

In [ ]:
classifier = knn(n_neighbors =3)                              # creating a KNN model

In [ ]:
classifier.fit(x,y)                                           # training the data

KNeighborsClassifier(n_neighbors=3)

In [ ]:
x_test = np.array([6,6])
y_predict = classifier.predict([x_test])                      # prediction using the model

In [ ]:
y_predict

array(['N'], dtype=object)

In [ ]:
x_test = np.array([4,2])

In [ ]:
classifier = knn(n_neighbors = 3, weights = 'distance')
classifier.fit(x,y)
y_predict = classifier.predict([x_test])

In [ ]:
y_predict

array(['N'], dtype=object)

In [ ]:
x_test = np.array([4.2,3.8])
y_predict = classifier.predict([x_test])                      # prediction using the model
y_predict

array(['P'], dtype=object)

### KNN activity | as k increases accuracy decreases


In [ ]:
from sklearn.neighbors import KNeighborsRegressor as knn1                  # TARGET IS continiuos so we are using regressor
df1 = pd.read_csv("/content/knn1.csv")

In [ ]:
df1

Height  Age  Weight
0    5.00   45      77
1    5.11   26      47
2    5.60   30      55
3    5.90   34      59
4    4.80   40      72
5    5.80   36      60
6    5.30   19      40
7    5.80   28      60
8    5.50   23      45
9    5.60   32      58

In [ ]:
x=df.iloc[:,:-1].values
y=df.iloc[:,:2].values

In [ ]:
x

array([[2, 4],
       [4, 6],
       [4, 4],
       [4, 2],
       [6, 4],
       [6, 2]])

In [ ]:
y

array([[2, 4],
       [4, 6],
       [4, 4],
       [4, 2],
       [6, 4],
       [6, 2]])

In [ ]:
classifier=knn1(n_neighbors = 3)

In [ ]:
classifier.fit(x,y)                                           # training the data

KNeighborsRegressor(n_neighbors=3)

In [ ]:
x_test = np.array([4.5,26])
y_predict = classifier.predict([x_test])

In [ ]:
y_predict

array([[4.66666667, 4.66666667]])

In [ ]:
classifier = knn1(n_neighbors = 4)

In [ ]:
classifier.fit(x,y)
x_test = np.array([5.5,26])
y_predict = classifier.predict([x_test])

In [ ]:
y_predict

array([[4. , 4.5]])

In [ ]:
classifier = knn1(n_neighbors = 5)
classifier.fit(x,y)
x_test = np.array([4.5,26])
y_predict = classifier.predict([x_test])                          # training the data


In [ ]:
#mse as x axis
y_predict

array([[4., 4.]])

### KNN - heart dataset

In [ ]:
from sklearn.neighbors import KNeighborsClassifier as heart                  # TARGET justhas 1 and 0 so we are using classifeir
df2 = pd.read_csv("/content/heart.csv")
df2

age  sex  chest_pain_type  resting_bp  cholestoral  fasting_blood_sugar  \
0     63    1                3         145          233                    1   
1     37    1                2         130          250                    0   
2     41    0                1         130          204                    0   
3     56    1                1         120          236                    0   
4     57    0                0         120          354                    0   
..   ...  ...              ...         ...          ...                  ...   
298   57    0                0         140          241                    0   
299   45    1                3         110          264                    0   
300   68    1                0         144          193                    1   
301   57    1                0         130          131                    0   
302   57    0                1         130          236                    0   

     restecg  max_hr  exang  oldpeak  slope  num_major_vessels  thal  target  
0          0     150      0      2.3      0                  0     1       1  
1          1     187      0      3.5      0                  0     2       1  
2          0     172      0      1.4      2                  0     2       1  
3          1     178      0      0.8      2                  0     2       1  
4          1     163      1      0.6      2                  0     2       1  
..       ...     ...    ...      ...    ...                ...   ...     ...  
298        1     123      1      0.2      1                  0     3       0  
299        1     132      0      1.2      1                  0     3       0  
300        1     141      0      3.4      1                  2     3       0  
301        1     115      1      1.2      1                  1     3       0  
302        0     174      0      0.0      1                  1     2       0  

[303 rows x 14 columns]

In [ ]:
df2.isnull().sum()

age                    0
sex                    0
chest_pain_type        0
resting_bp             0
cholestoral            0
fasting_blood_sugar    0
restecg                0
max_hr                 0
exang                  0
oldpeak                0
slope                  0
num_major_vessels      0
thal                   0
target                 0
dtype: int64

In [ ]:
#Splitting the dataset into feature columns and target column
X=df2.drop(columns=['target'])
Y=df2[['target']]

In [ ]:
#Normalizing feature columns
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x = scaler.fit_transform(X)
x

array([[ 0.9521966 ,  0.68100522,  1.97312292, ..., -2.27457861,
        -0.71442887, -2.14887271],
       [-1.91531289,  0.68100522,  1.00257707, ..., -2.27457861,
        -0.71442887, -0.51292188],
       [-1.47415758, -1.46841752,  0.03203122, ...,  0.97635214,
        -0.71442887, -0.51292188],
       ...,
       [ 1.50364073,  0.68100522, -0.93851463, ..., -0.64911323,
         1.24459328,  1.12302895],
       [ 0.29046364,  0.68100522, -0.93851463, ..., -0.64911323,
         0.26508221,  1.12302895],
       [ 0.29046364, -1.46841752,  0.03203122, ..., -0.64911323,
         0.26508221, -0.51292188]])

In [ ]:
#Splitting into training and testing datasets
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =train_test_split(x,Y,test_size=0.3,random_state=85)

len(x_train),len(x_test),len(y_train),len(y_test)

(212, 91, 212, 91)

In [ ]:
classifier = heart(n_neighbors = 5)
classifier.fit(x_train, y_train)


/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(x_test)


In [ ]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
accuracy = np.round(accuracy, 3)
print("Accuracy is", accuracy * 100, "%")


Accuracy is 79.10000000000001 %


In [ ]:
error_rate=[]#list that will store the average error rate value of k
for i in range (1,31):  #Took the range of k from 1 to 30
    clf=heart(n_neighbors=i)
    clf.fit(x_train,y_train)
    predict=clf.predict(x_test)
    error_rate.append(np.mean(pred!=y_test))
erro_rate

In [ ]:
#plotting the error rate vs k graph
plt.figure(figsize=(12,6))
plt.plot(range(1,31),error_rate,marker="o",markerfacecolor="green",
         linestyle="dashed",color="red",markersize=15)
plt.title("Error rate vs k value",fontsize=20)
plt.xlabel("k- values",fontsize=20)
plt.ylabel("error rate",fontsize=20)
plt.xticks(range(1,31))
plt.show()