
**# SVM **

In [ ]:
import pandas as pd
import numpy as np
from sklearn import model_selection
from sklearn .tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [ ]:
col_names = ['pregnant','glucose','bp','skin','insulin','bmi','pedigree','age','label']


In [ ]:
# Load the dataset
pima = pd.read_csv("/content/pima-indians-diabetes.csv", header = None , names = col_names)

In [ ]:
feature_cols = ['pregnant','insulin','bmi','pedigree','age','glucose','bp']


In [ ]:
X = pima[feature_cols]  # Features
Y = pima.label             # Target Variable

In [ ]:
regressor = DecisionTreeClassifier()
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.25,random_state = 0)
regressor.fit(x_train,y_train)                    # training of classifier

from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = regressor, X=X, y=Y, cv=5)
accuracies

array([0.74675325, 0.67532468, 0.66883117, 0.79738562, 0.76470588])

In [ ]:
accuracies.mean()

0.7306001188354129

In [ ]:
from sklearn.svm import SVC

In [ ]:
svm = SVC(kernel = 'poly')

In [ ]:
model = svm.fit(x_train,y_train)

In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = model, X=X , y=Y, cv=5)
accuracies

array([0.77272727, 0.75974026, 0.75974026, 0.78431373, 0.75163399])

In [ ]:
accuracies.mean()

0.7656311009252186

In [ ]:
accuracies = cross_val_score(estimator = model, X=X , y=Y, cv=50)
accuracies


array([0.875     , 0.6875    , 0.6875    , 0.75      , 0.75      ,
       0.6875    , 0.875     , 0.6875    , 0.8125    , 0.6875    ,
       0.8125    , 0.75      , 0.8125    , 0.5       , 0.9375    ,
       0.875     , 0.625     , 0.75      , 0.53333333, 0.73333333,
       0.66666667, 0.73333333, 0.73333333, 0.8       , 0.8       ,
       0.86666667, 0.8       , 0.8       , 0.73333333, 0.8       ,
       0.6       , 0.73333333, 0.8       , 0.8       , 0.66666667,
       0.73333333, 0.86666667, 0.8       , 1.        , 0.66666667,
       0.73333333, 0.86666667, 0.66666667, 0.66666667, 0.8       ,
       0.8       , 0.6       , 0.73333333, 0.8       , 0.8       ])

In [ ]:
accuracies.mean()

0.7539166666666666